# Generated by Django 5.1.1 on 2024-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('ingles', 'Inglês'), ('ed_fisica', 'Educação Física'), ('artes', 'Artes'), ('literatura', 'Literatura'), ('quimica', 'Química'), ('fisica', 'Física'), ('biologia', 'Biologia')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_date', models.DateField()),
                ('courses', models.ManyToManyField(related_name='students', to='student.course')),
            ],
        ),
    ]
